services:
  neo4j-db:
    image: neo4j:latest
    container_name: neo4j-db-container
    ports:
      - "${DATABASE_WEB_PORT_E:-7474}:${DATABASE_WEB_PORT_I:-7474}" # Neo4j browser web interface
      - "${DATABASE_BOLT_PORT_E:-7687}:${DATABASE_BOLT_PORT_E:-7687}" # Bolt protocol for database connections
    environment:
      NEO4J_AUTH: "neo4j/TestPassword" # Replace with your desired username/password
      NEO4JLABS_PLUGINS: '["apoc","graph-data-science"]' # Add APOC plugin
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*, gds.*"
      NEO4J_dbms_security_procedures_allowlist: "apoc.*, gds.*"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_dbms_memory_pagecache_size: "2G"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_dbms_connector_bolt_listen__address: "0.0.0.0:${DATABASE_BOLT_PORT_I:-7687}"
      NEO4J_dbms_connector_http_listen__address: "0.0.0.0:${DATABASE_WEB_PORT_I:-7474}"
    volumes:
      - ./neo4j-db/data:/data # Data directory for database files
      - ./neo4j-db/logs:/logs # Logs directory
      - ./neo4j-db/import:/import # Directory for importing files
      - ./neo4j-db/plugins:/plugins # Directory for plugins
    restart: unless-stopped

  api-service:
    build:
      context: ./API # Build context is the /API/ folder
      dockerfile: Dockerfile # Uses the Dockerfile within the /API/ folder
    container_name: api-container
    ports:
      - "${API_PORT_E:-8085}:${API_PORT_I:-3000}" # Exposes the API on ports external:internal
    env_file:
      - ./.env # Loads environment variables from the .env file
    environment:
      NEO4J_URI: "bolt://neo4j-db-container:${DATABASE_BOLT_PORT_I:-7687}" # Neo4j connection string
      NEO4J_USER: ${NEO4J_USER}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      CUDA_VISIBLE_DEVICES: "0"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    runtime: nvidia
    volumes:
      - ./API:/app # Mounts the /API/ folder to /app in the container
    depends_on:
      - neo4j-db # Ensures Neo4j starts before the Python app
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-container
    ports:
      - "${OLLAMA_PORT_E:-11434}:${OLLAMA_PORT_I:-11434}"
    volumes:
      - ./ollama:/var/lib/ollama
      - ./ollama_models:/root/.ollama
    runtime: nvidia # Enable NVIDIA runtime for GPU access
    environment:
      - NVIDIA_VISIBLE_DEVICES=all # Expose all GPUs
      - NVIDIA_DRIVER_CAPABILITIES=all # Grant all driver capabilities
    

    restart: unless-stopped

networks:
  default:
    external: false
